### ISSUE TITLE
Error processing argument at index 0 conversion failure from at TypeError (native) at toggleFullScreen (Linux)

### ISSUE THREAD

**Issue by joseluisq** [feross/webtorrent-app#128]
In Linux (Fedora 23 x64) when I click on the full screen menu

![Error processing argument at index 0 conversion failure from at TypeError (native) at toggleFullScreen (Linux)](https://cloud.githubusercontent.com/assets/1700322/13692057/fd3b083a-e70b-11e5-952a-45aa2d07f103.png)

appears the popup with following error:

```sh
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from 
    at TypeError (native)
    at toggleFullScreen (/home/joseluis/webtorrent-app/main/menu.js:30:18)
    at MenuItem.click (/home/joseluis/webtorrent-app/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/api/lib/menu-item.js:69:18)
    at Function.delegate.executeCommand (/home/joseluis/webtorrent-app/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/api/lib/menu.js:128:69)
```

**Comment by feross** [comment]
Working on it.

**Comment by joseluisq** [comment]
Cool! :+1:
